// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRxrXtdovNi0u7fg0eAdotxdZ1XPn70xo',
    appId: '1:883679893472:web:427dfab3210a1cbd37fd85',
    messagingSenderId: '883679893472',
    projectId: 'p3l-reusemart',
    authDomain: 'p3l-reusemart.firebaseapp.com',
    databaseURL:
        'https://p3l-reusemart-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'p3l-reusemart.firebasestorage.app',
    measurementId: 'G-QRXNG32E96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBig-jiDiGA8bhpTUKpNeBmhd6XhEhnZVU',
    appId: '1:883679893472:android:9b7025da1ee544e337fd85',
    messagingSenderId: '883679893472',
    projectId: 'p3l-reusemart',
    databaseURL:
        'https://p3l-reusemart-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'p3l-reusemart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUN7X8E7hOy-ITyYhOgOezR9H_YW5tjJg',
    appId: '1:883679893472:ios:d205eebe8949888d37fd85',
    messagingSenderId: '883679893472',
    projectId: 'p3l-reusemart',
    databaseURL:
        'https://p3l-reusemart-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'p3l-reusemart.firebasestorage.app',
    iosBundleId: 'com.example.p3lReusemart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUN7X8E7hOy-ITyYhOgOezR9H_YW5tjJg',
    appId: '1:883679893472:ios:d205eebe8949888d37fd85',
    messagingSenderId: '883679893472',
    projectId: 'p3l-reusemart',
    databaseURL:
        'https://p3l-reusemart-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'p3l-reusemart.firebasestorage.app',
    iosBundleId: 'com.example.p3lReusemart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRxrXtdovNi0u7fg0eAdotxdZ1XPn70xo',
    appId: '1:883679893472:web:aa82d6053b1c140037fd85',
    messagingSenderId: '883679893472',
    projectId: 'p3l-reusemart',
    authDomain: 'p3l-reusemart.firebaseapp.com',
    databaseURL:
        'https://p3l-reusemart-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'p3l-reusemart.firebasestorage.app',
    measurementId: 'G-N5CQ3RS7S0',
  );
}
